In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import sklearn

In [2]:
df = pd.read_csv("heart_disease_uci.csv")
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(8)
memory usage: 115.1+ KB

In [4]:
df = df.drop(columns = ["id" , "ca"])

In [5]:
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,thal,num
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,normal,2
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,normal,0

In [6]:
df = pd.get_dummies(df , drop_first = True)

In [7]:
df.head()

,age,trestbps,chol,thalch,oldpeak,num,sex_Male,dataset_Hungary,dataset_Switzerland,dataset_VA Long Beach,...,cp_non-anginal,cp_typical angina,fbs_True,restecg_normal,restecg_st-t abnormality,exang_True,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,150.0,2.3,0,True,False,False,False,...,False,True,True,False,False,False,False,False,False,False
1,67,160.0,286.0,108.0,1.5,2,True,False,False,False,...,False,False,False,False,False,True,True,False,True,False
2,67,120.0,229.0,129.0,2.6,1,True,False,False,False,...,False,False,False,False,False,True,True,False,False,True
3,37,130.0,250.0,187.0,3.5,0,True,False,False,False,...,True,False,False,True,False,False,False,False,True,False
4,41,130.0,204.0,172.0,1.4,0,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       920 non-null    int64
 1   trestbps                  861 non-null    float64
 2   chol                      890 non-null    float64
 3   thalch                    865 non-null    float64
 4   oldpeak                   858 non-null    float64
 5   num                       920 non-null    int64
 6   sex_Male                  920 non-null    bool
 7   dataset_Hungary           920 non-null    bool
 8   dataset_Switzerland       920 non-null    bool
 9   dataset_VA Long Beach     920 non-null    bool
 10  cp_atypical angina        920 non-null    bool
 11  cp_non-anginal            920 non-null    bool
 12  cp_typical angina         920 non-null    bool
 13  fbs_True                  920 non-null    bool
 14  restecg_normal            920 non-null    bool
 15  restecg_st-t abnormality  920 non-null    bool
 16  exang_True                920 non-null    bool
 17  slope_flat                920 non-null    bool
 18  slope_upsloping           920 non-null    bool
 19  thal_normal               920 non-null    bool
 20  thal_reversable defect    920 non-null    bool
dtypes: bool(15), float64(4), int64(2)
memory usage: 56.7 KB

In [9]:
df.fillna(df.median(numeric_only = True) , inplace = True )
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       920 non-null    int64
 1   trestbps                  920 non-null    float64
 2   chol                      920 non-null    float64
 3   thalch                    920 non-null    float64
 4   oldpeak                   920 non-null    float64
 5   num                       920 non-null    int64
 6   sex_Male                  920 non-null    bool
 7   dataset_Hungary           920 non-null    bool
 8   dataset_Switzerland       920 non-null    bool
 9   dataset_VA Long Beach     920 non-null    bool
 10  cp_atypical angina        920 non-null    bool
 11  cp_non-anginal            920 non-null    bool
 12  cp_typical angina         920 non-null    bool
 13  fbs_True                  920 non-null    bool
 14  restecg_normal            920 non-null    bool
 15  restecg_st-t abnormality  920 non-null    bool
 16  exang_True                920 non-null    bool
 17  slope_flat                920 non-null    bool
 18  slope_upsloping           920 non-null    bool
 19  thal_normal               920 non-null    bool
 20  thal_reversable defect    920 non-null    bool
dtypes: bool(15), float64(4), int64(2)
memory usage: 56.7 KB

In [10]:
df = df.replace({True: 1, False: 0})
df["num"] = df["num"].replace({1: 1, 2: 1, 3: 1, 4: 1})

C:\Users\hp\AppData\Local\Temp\ipykernel_26092\3053822972.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({True: 1, False: 0})

In [11]:
df

,age,trestbps,chol,thalch,oldpeak,num,sex_Male,dataset_Hungary,dataset_Switzerland,dataset_VA Long Beach,...,cp_non-anginal,cp_typical angina,fbs_True,restecg_normal,restecg_st-t abnormality,exang_True,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,150.0,2.3,0,1,0,0,0,...,0,1,1,0,0,0,0,0,0,0
1,67,160.0,286.0,108.0,1.5,1,1,0,0,0,...,0,0,0,0,0,1,1,0,1,0
2,67,120.0,229.0,129.0,2.6,1,1,0,0,0,...,0,0,0,0,0,1,1,0,0,1
3,37,130.0,250.0,187.0,3.5,0,1,0,0,0,...,1,0,0,1,0,0,0,0,1,0
4,41,130.0,204.0,172.0,1.4,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,127.0,333.0,154.0,0.0,1,0,0,0,1,...,0,0,1,0,1,0,0,0,0,0
916,62,130.0,139.0,140.0,0.5,0,1,0,0,1,...,0,1,0,0,1,0,0,0,0,0
917,55,122.0,223.0,100.0,0.0,1,1,0,0,1,...,0,0,1,0,1,0,0,0,0,0
918,58,130.0,385.0,140.0,0.5,0,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
919,62,120.0,254.0,93.0,0.0,1,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       920 non-null    int64
 1   trestbps                  920 non-null    float64
 2   chol                      920 non-null    float64
 3   thalch                    920 non-null    float64
 4   oldpeak                   920 non-null    float64
 5   num                       920 non-null    int64
 6   sex_Male                  920 non-null    int64
 7   dataset_Hungary           920 non-null    int64
 8   dataset_Switzerland       920 non-null    int64
 9   dataset_VA Long Beach     920 non-null    int64
 10  cp_atypical angina        920 non-null    int64
 11  cp_non-anginal            920 non-null    int64
 12  cp_typical angina         920 non-null    int64
 13  fbs_True                  920 non-null    int64
 14  restecg_normal            920 non-null    int64
 15  restecg_st-t abnormality  920 non-null    int64
 16  exang_True                920 non-null    int64
 17  slope_flat                920 non-null    int64
 18  slope_upsloping           920 non-null    int64
 19  thal_normal               920 non-null    int64
 20  thal_reversable defect    920 non-null    int64
dtypes: float64(4), int64(17)
memory usage: 151.1 KB

In [13]:
X = df.drop(columns = ["num"])
y = df["num"]

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import RobustScaler
from sklearn.tree import DecisionTreeClassifier 
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score , precision_score  , recall_score , f1_score , classification_report , confusion_matrix

In [15]:
X_test , X_train , y_test , y_train = train_test_split(X,y , random_state = 42 , test_size = 0.2)

In [16]:
scaler = RobustScaler()

In [17]:
X_train[["age" , "trestbps" , "chol" , "thalch" , "oldpeak"]] = scaler.fit_transform(X_train[["age" , "trestbps" , "chol" , "thalch" , "oldpeak"]])
X_test [["age" , "trestbps" , "chol" , "thalch" , "oldpeak"]] = scaler.transform(X_test [["age" , "trestbps" , "chol" , "thalch" , "oldpeak"]])

In [35]:
LogisticRegression = LogisticRegression (max_iter = 1000 , random_state = 42 , class_weight = "balanced" )
LogisticRegression.fit(X_train , y_train)
y_predict = LogisticRegression.predict(X_test)

In [36]:
accuracy = accuracy_score(y_test , y_predict)
precision = precision_score(y_test , y_predict)
recall = recall_score(y_test , y_predict)
f1 = f1_score(y_test , y_predict)
classification = classification_report(y_test , y_predict)
matrix = confusion_matrix(y_test , y_predict)

In [22]:
print(df["num"].value_counts())

num
1    509
0    411
Name: count, dtype: int64

In [38]:
print("=" * 50)
print("Model Evaluation Metrics")
print("=" * 50)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n" + "=" * 50)
print("Classification Report")
print("=" * 50)
print(classification)

print("=" * 50)
print("Confusion Matrix")
print("=" * 50)
print(matrix)

==================================================
Model Evaluation Metrics
==================================================
Accuracy  : 0.8125
Precision : 0.8227
Recall    : 0.8350
F1 Score  : 0.8288

==================================================
Classification Report
==================================================
              precision    recall  f1-score   support

           0       0.80      0.79      0.79       336
           1       0.82      0.83      0.83       400

    accuracy                           0.81       736
   macro avg       0.81      0.81      0.81       736
weighted avg       0.81      0.81      0.81       736

==================================================
Confusion Matrix
==================================================
[[264  72]
 [ 66 334]]

In [42]:
DecisionTree = DecisionTreeClassifier (class_weight = "balanced" , random_state = 42 )
DecisionTree.fit(X_train , y_train)
y_predict = DecisionTree.predict(X_test)

In [43]:
accuracy = accuracy_score(y_test , y_predict)
precision = precision_score(y_test , y_predict)
recall = recall_score(y_test , y_predict)
f1 = f1_score(y_test , y_predict)
classification = classification_report(y_test , y_predict)
matrix = confusion_matrix(y_test , y_predict)

In [44]:
print("=" * 50)
print("Model Evaluation Metrics")
print("=" * 50)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n" + "=" * 50)
print("Classification Report")
print("=" * 50)
print(classification)

print("=" * 50)
print("Confusion Matrix")
print("=" * 50)
print(matrix)

==================================================
Model Evaluation Metrics
==================================================
Accuracy  : 0.7174
Precision : 0.7212
Recall    : 0.7825
F1 Score  : 0.7506

==================================================
Classification Report
==================================================
              precision    recall  f1-score   support

           0       0.71      0.64      0.67       336
           1       0.72      0.78      0.75       400

    accuracy                           0.72       736
   macro avg       0.72      0.71      0.71       736
weighted avg       0.72      0.72      0.72       736

==================================================
Confusion Matrix
==================================================
[[215 121]
 [ 87 313]]

In [53]:
RandomForest = RandomForestClassifier (max_depth = 20 , n_estimators = 300 , min_samples_leaf = 5 ,class_weight = "balanced" , random_state = 42 , n_jobs = -1)
RandomForest.fit(X_train , y_train)
y_predict = RandomForest.predict(X_test)

In [50]:
accuracy = accuracy_score(y_test , y_predict)
precision = precision_score(y_test , y_predict)
recall = recall_score(y_test , y_predict)
f1 = f1_score(y_test , y_predict)
classification = classification_report(y_test , y_predict)
matrix = confusion_matrix(y_test , y_predict)


print("=" * 50)
print("Model Evaluation Metrics")
print("=" * 50)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n" + "=" * 50)
print("Classification Report")
print("=" * 50)
print(classification)

print("=" * 50)
print("Confusion Matrix")
print("=" * 50)
print(matrix)

==================================================
Model Evaluation Metrics
==================================================
Accuracy  : 0.8057
Precision : 0.7927
Recall    : 0.8700
F1 Score  : 0.8296

==================================================
Classification Report
==================================================
              precision    recall  f1-score   support

           0       0.82      0.73      0.77       336
           1       0.79      0.87      0.83       400

    accuracy                           0.81       736
   macro avg       0.81      0.80      0.80       736
weighted avg       0.81      0.81      0.80       736

==================================================
Confusion Matrix
==================================================
[[245  91]
 [ 52 348]]

In [54]:
Knn = KNeighborsClassifier(n_neighbors = 5 , n_jobs = -1)
Knn.fit(X_train , y_train)
y_predict = Knn.predict(X_test)

In [55]:
accuracy = accuracy_score(y_test , y_predict)
precision = precision_score(y_test , y_predict)
recall = recall_score(y_test , y_predict)
f1 = f1_score(y_test , y_predict)
classification = classification_report(y_test , y_predict)
matrix = confusion_matrix(y_test , y_predict)


print("=" * 50)
print("Model Evaluation Metrics")
print("=" * 50)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n" + "=" * 50)
print("Classification Report")
print("=" * 50)
print(classification)

print("=" * 50)
print("Confusion Matrix")
print("=" * 50)
print(matrix)

==================================================
Model Evaluation Metrics
==================================================
Accuracy  : 0.8016
Precision : 0.7940
Recall    : 0.8575
F1 Score  : 0.8245

==================================================
Classification Report
==================================================
              precision    recall  f1-score   support

           0       0.81      0.74      0.77       336
           1       0.79      0.86      0.82       400

    accuracy                           0.80       736
   macro avg       0.80      0.80      0.80       736
weighted avg       0.80      0.80      0.80       736

==================================================
Confusion Matrix
==================================================
[[247  89]
 [ 57 343]]

In [57]:
SVM = SVC(kernel = "rbf" , class_weight = "balanced" , random_state = 42)
SVM.fit(X_train , y_train)
y_predict = SVM.predict(X_test)

In [58]:
accuracy = accuracy_score(y_test , y_predict)
precision = precision_score(y_test , y_predict)
recall = recall_score(y_test , y_predict)
f1 = f1_score(y_test , y_predict)
classification = classification_report(y_test , y_predict)
matrix = confusion_matrix(y_test , y_predict)


print("=" * 50)
print("Model Evaluation Metrics")
print("=" * 50)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\n" + "=" * 50)
print("Classification Report")
print("=" * 50)
print(classification)

print("=" * 50)
print("Confusion Matrix")
print("=" * 50)
print(matrix)

==================================================
Model Evaluation Metrics
==================================================
Accuracy  : 0.7976
Precision : 0.7820
Recall    : 0.8700
F1 Score  : 0.8237

==================================================
Classification Report
==================================================
              precision    recall  f1-score   support

           0       0.82      0.71      0.76       336
           1       0.78      0.87      0.82       400

    accuracy                           0.80       736
   macro avg       0.80      0.79      0.79       736
weighted avg       0.80      0.80      0.80       736

==================================================
Confusion Matrix
==================================================
[[239  97]
 [ 52 348]]